title: 'WEBANT Services<i class="logoAuthor">by Anthony Normand</i>'
default_lang: fr
author:
  name: 'Anthony NORMAND'
  email: antho.normand@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Webant service site web'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
